### ISSUE TITLE
mysqld.cnf.group-mode.patch not in folder mysql

### ISSUE THREAD

**Issue by JorgeRP** [waynemerricks/rivendellubuntuxenial#1]
Two scripts call this file, but this not exists...
Regards

**Comment by waynemerricks** [comment]
Apologies, in amongst the rush the script changes were committed but I forgot to add the script.  This is in release 1.2 or just download the patch directly from github.

**Comment by JorgeRP** [comment]
Thanks,
I made the installation with version 1.2 and it worked very well. I have two
problems after installing, I will publish to improve installation. Thank
you very much

2016-05-22 13:24 GMT-03:00 Wayne Merricks notifications@github.com:
